name: Jeremy Olander
favicon: null
layout_spectrum: 0.25588
typography_spectrum: 0.21671
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#000000'
    - '#2b2b2b'
    - '#757575'
    - '#c3c3c3'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
